package com.gslab.parivahan.security;

import java.security.Key;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

import io.jsonwebtoken.impl.crypto.MacProvider;

/*
 * 
 * @author Swapnil Kashid
 * 
 * */

@Configuration
@ConfigurationProperties(prefix = "parivahan.security.jwt")
public class ParivahanJwtSettings {
	/**
	 * {@link ICesJwtToken} will expire after this time.
	 */
	private String tokenExpirationTime;
	/**
	 * anonymous token will expire after this time.
	 */
	private String anonymousTokenExpirationTime;

	/**
	 * Token issuer.
	 */
	private String tokenIssuer;

	/**
	 * Key is used to sign {@link ICesJwtToken}.
	 */
	private String tokenSigningKey;

	private Key autoGeneratedTokenSigningKey = MacProvider.generateKey();

	/**
	 * {@link ICesJwtToken} can be refreshed during this timeframe.
	 */
	private String refreshTokenExpTime;

	/**
	 * @return the autoGeneratedTokenSigningKey
	 */
	public Key getAutoGeneratedTokenSigningKey() {
		return autoGeneratedTokenSigningKey;
	}

	public Integer getRefreshTokenExpTime() {
		return Integer.parseInt(refreshTokenExpTime);
	}

	public void setRefreshTokenExpTime(Integer refreshTokenExpTime) {
		this.refreshTokenExpTime = refreshTokenExpTime.toString();
	}

	public Integer getTokenExpirationTime() {
		return Integer.parseInt(tokenExpirationTime);
	}

	public void setTokenExpirationTime(Integer tokenExpirationTime) {
		this.tokenExpirationTime = tokenExpirationTime.toString();
	}

	
	public Integer getAnonymousTokenExpirationTime() {
		return Integer.parseInt(anonymousTokenExpirationTime);
	}

	public void setAnonymousTokenExpirationTime(Integer anonymousTokenExpirationTime) {
		this.anonymousTokenExpirationTime = anonymousTokenExpirationTime.toString();
	}

	public String getTokenIssuer() {
		return tokenIssuer;
	}

	public void setTokenIssuer(String tokenIssuer) {
		this.tokenIssuer = tokenIssuer;
	}

	public String getTokenSigningKey() {
		return tokenSigningKey;
	}

	public void setTokenSigningKey(String tokenSigningKey) {
		this.tokenSigningKey = tokenSigningKey;
	}
}
